spring.datasource.url=jdbc:mysql://mysql:3306/test?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=12345678
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.liquibase.enabled=true
spring.jpa.show-sql=true

server.servlet.context-path=/api

jwt.expiration=30000000
jwt.secret=odfhgoshgflkasjnrflksnjhdfliojhweop[ij;sldmfpowdzfg

server.port=8081
